#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# bootstrap.sh — CureIndia
# Generated by graduation-blueprint on 2026-06-21
# Run: bash bootstrap.sh [target-directory]
# ============================================================

REPO_NAME="cure-india-app"
TARGET="${1:-../$REPO_NAME}"
IDEA_DIR="$(cd "$(dirname "$0")" && pwd)"  # the graduated idea folder

echo ""
echo "🚀 Bootstrapping $REPO_NAME into $TARGET"
echo ""

# ── 1. Create folder structure ───────────────────────────────
mkdir -p "$TARGET"/{src/app/api,src/app/\(auth\),src/app/\(dashboard\),src/app/hospitals,src/app/vault,src/app/quotes,src/app/concierge}
mkdir -p "$TARGET"/src/{components,lib,hooks,types}
mkdir -p "$TARGET"/{tests,docs/decisions,.agents/skills,.github,prisma}

echo "✓ Folder structure created"

# ── 2. Write AGENTS.md ───────────────────────────────────────
cat > "$TARGET/AGENTS.md" << 'AGENTS_EOF'
# AGENTS.md — CureIndia

## What this repo is
CureIndia is a trust-centered, compliance-first marketplace connecting international patients with JCI/NABH accredited Indian hospitals and vetted local concierge services. It features standardized packaging, an end-to-end encrypted medical record vault, a multi-quote comparison portal, and structured concierge booking. The project is currently building its Phase 1 MVP.

## Codebase layout
- `src/app/` — Next.js page routes, layouts, and API endpoints (app router).
- `src/components/` — Shared, reusable UI components and specialized modules (e.g., encryption panels).
- `src/lib/` — Shared utility libraries: cryptographic functions, DB client, and third-party integrations.
- `src/hooks/` — Custom React hooks (authentication, encryption/decryption state, upload progress).
- `src/types/` — Shared TypeScript type declarations for users, quotes, and transactions.
- `prisma/` — Database schema definitions (PostgreSQL) and seeding scripts.
- `tests/` — Component, unit, integration, and security/encryption test suites.
- `docs/` — System architecture, data models, API specifications, and Architecture Decision Records (ADRs).
- `.agents/` — Agent instructions, guidelines, and skills.

## How to run locally
1. Install dependencies:
   ```bash
   npm install
   ```
2. Copy environment template and fill values:
   ```bash
   cp .env.example .env
   ```
3. Set up and migrate the database:
   ```bash
   npx prisma migrate dev
   npx prisma db seed
   ```
4. Start the local development server:
   ```bash
   npm run dev
   ```

## Agent behaviour
- **TDD Preferred:** Write corresponding unit or integration tests in `tests/` alongside implementation files, not afterwards.
- **Scope Isolation:** Modify files exclusively related to the current feature branch. Never make arbitrary code changes in unrelated directories.
- **Commit Format:** `[scope] short description` — e.g., `[vault] add client-side AES chunking` or `[auth] secure session routing`.
- **Docs Sync:** Always update architectural diagrams or specifications in `docs/` if modifying database schemas, api routes, or key cryptographic flows.

## Code conventions
- **Language:** TypeScript strictly (avoid `any`, enforce strict types).
- **Styling:** CSS Modules or Tailwind CSS. Enforce clean, responsive component design.
- **Formatting:** Prettier for formatting, ESLint for lint rules.
- **Crypto:** Enforce standard browser `crypto.subtle` APIs for client-side encryption. Keep keys in-memory.

## What agents must NOT do
- **No Plaintext Medical Records:** Never write logic that uploads unencrypted patient medical PDFs/images to S3 or stores decryption keys in database tables.
- **No Referral Commission Logic:** Do NOT write code that calculates hospital bill percentage splits or referral fees. All hospital transactions must use B2B SaaS listing subscriptions or flat-rate booking fees.
- **No Direct Schema Updates:** Never alter the database schema without writing a corresponding Prisma migration file.
AGENTS_EOF
echo "✓ AGENTS.md written"

# ── 3. Scaffold skills ───────────────────────────────────────

# --- Core Skills ---
mkdir -p "$TARGET/.agents/skills/dev-setup"
cat > "$TARGET/.agents/skills/dev-setup/dev-setup.md" << 'SKILL_EOF'
---
name: dev-setup
description: >
  Gets any contributor from zero to running. Documents env vars,
  dependencies, seed data, and common setup errors.
---
# Dev Setup

## Prerequisites
- Node.js (v18+ or v20+)
- PostgreSQL (running locally or via Docker)

## Installation
1. Clone the repository and navigate into it.
2. Install dependencies:
   ```bash
   npm install
   ```
3. Copy the environment variables template and configure the values:
   ```bash
   cp .env.example .env
   ```
4. Initialize the Prisma database client:
   ```bash
   npx prisma generate
   ```
5. Apply database migrations and seed default JCI/NABH hospitals and demo credentials:
   ```bash
   npx prisma migrate dev
   npx prisma db seed
   ```
6. Run the local Next.js development server:
   ```bash
   npm run dev
   ```
   Open [http://localhost:3000](http://localhost:3000) to view the application.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/code-review"
cat > "$TARGET/.agents/skills/code-review/code-review.md" << 'SKILL_EOF'
---
name: code-review
description: >
  Reviews code for correctness, consistency with conventions,
  missing tests, and scope creep. Does not rewrite — annotates and explains.
---
# Code Review

## Core Guidelines
1. **Accreditation Checks:** Ensure any code handling hospital registration enforces NABH or JCI accreditation checks.
2. **Zero-Knowledge Check:** Double-check that patient medical documents are never sent in plaintext. All API uploads must expect encrypted payloads.
3. **No Commission Logic:** Ensure no referral calculation features exist. The listing must strictly use monthly SaaS metrics.
4. **Strict TypeScript:** Reject the use of `any` types. Enforce proper interfaces in `src/types/`.
5. **Test Coverage:** Verify that new features or routing endpoints have matching unit/integration tests in `tests/`.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/debug"
cat > "$TARGET/.agents/skills/debug/debug.md" << 'SKILL_EOF'
---
name: debug
description: >
  Systematic diagnosis of errors — reads logs, traces the call
  stack, identifies root cause, proposes fix with explanation.
---
# Debug

## Debugging Checklist
1. **Decryption Errors:** Check if the browser WebCrypto key import fails. Verify that the public key matches the target hospital's registered public key format (PEM/SPKI).
2. **Database Queries:** If database operations fail, check Prisma queries. Verify migrations by running `npx prisma status`.
3. **S3 File Uploads:** Ensure CORS settings in S3 permit direct POST uploads from the client browser.
4. **Auth Expirations:** If session validation fails, check NextAuth cookies and secret hashes.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/write-tests"
cat > "$TARGET/.agents/skills/write-tests/write-tests.md" << 'SKILL_EOF'
---
name: write-tests
description: >
  Writes unit and integration tests for a given module or function.
  Covers happy path, edge cases, and error states. Uses the project's test framework.
---
# Write Tests

## Testing Guidelines
- Jest for unit testing cryptographic logic and utility functions.
- Playwright/Cypress for E2E testing of the quote creation flow, patient registry, and role redirects.
- Place tests under the `tests/` directory mirroring the `src/` layout.
- Always include test coverage for client-side cryptographic functions in `src/lib/crypto.ts`.
SKILL_EOF

# --- Product-Specific Skills ---

mkdir -p "$TARGET/.agents/skills/auth-roles"
cat > "$TARGET/.agents/skills/auth-roles/auth-roles.md" << 'SKILL_EOF'
---
name: auth-roles
description: >
  Handles user authentication, signup onboarding wizards, and role-based access control.
---
# Auth & Roles

## Scope
- Files: `src/app/(auth)/`, `src/app/api/auth/`, `src/hooks/useAuth.ts`, `src/types/auth.d.ts`

## Requirements
- Support four roles: `Patient`, `Hospital`, `Agency`, `Admin`.
- Hospital reps must submit JCI/NABH certificate metadata during signup.
- Protect private routes using Next.js middleware checking role scopes.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/hospital-directory"
cat > "$TARGET/.agents/skills/hospital-directory/hospital-directory.md" << 'SKILL_EOF'
---
name: hospital-directory
description: >
  Manages hospital search directories, category filters, and credentials display.
---
# Hospital Directory

## Scope
- Files: `src/app/hospitals/`, `src/components/HospitalCard.tsx`, `prisma/schema.prisma`

## Guidelines
- Search logic should support location filters (Delhi, Mumbai, Bangalore) and clinical specialties (Cardiology, Orthopedics, Oncology).
- Display JCI and NABH badge marks clearly on verified hospitals.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/medical-vault"
cat > "$TARGET/.agents/skills/medical-vault/medical-vault.md" << 'SKILL_EOF'
---
name: medical-vault
description: >
  Implements zero-knowledge client-side encryption (AES-256-GCM) and secure upload routing.
---
# Medical Vault

## Scope
- Files: `src/lib/crypto.ts`, `src/hooks/useVault.ts`, `src/app/api/vault/`, `src/components/VaultUpload.tsx`

## Core Logic
1. Retrieve target hospital's public RSA key.
2. Generate browser-native symmetric AES-256 key.
3. Encrypt medical file using AES-256-GCM.
4. Encrypt the symmetric AES key using the hospital's public RSA key.
5. Post both the encrypted file blob (to S3) and the encrypted AES key to the backend.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/quote-portal"
cat > "$TARGET/.agents/skills/quote-portal/quote-portal.md" << 'SKILL_EOF'
---
name: quote-portal
description: >
  Manages quoting bids, hospital dashboards, and itemized packages compilation.
---
# Quote Portal

## Scope
- Files: `src/app/quotes/`, `src/app/api/quotes/`, `src/components/QuoteComparison.tsx`

## Core Workflow
- Patients create quote requests and link them to files in the Encrypted Vault.
- Target hospitals (max 3) download the encrypted symmetric keys and files.
- Hospital representatives upload itemized quotes detailing surgical procedures, local logistics, and concierge fees.
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/concierge-management"
cat > "$TARGET/.agents/skills/concierge-management/concierge-management.md" << 'SKILL_EOF'
---
name: concierge-management
description: >
  Manages concierge directories, booking checkouts, and visa checklist trackers.
---
# Concierge Management

## Scope
- Files: `src/app/concierge/`, `src/app/api/concierge/`, `src/components/VisaTracker.tsx`

## Features
- Vetted concierge directory showing hotel/transit listings.
- Indian e-medical visa tracker checklist.
- Unified booking system routing funds via flat-rate platform logistics package pricing (~₹15,000 margin per booking).
SKILL_EOF

mkdir -p "$TARGET/.agents/skills/multilingual-chat"
cat > "$TARGET/.agents/skills/multilingual-chat/multilingual-chat.md" << 'SKILL_EOF'
---
name: multilingual-chat
description: >
  Powers real-time chat with message translation APIs for clinical coordinators and translation service requests.
---
# Multilingual Chat

## Scope
- Files: `src/app/api/translate/`, `src/components/ChatWindow.tsx`, `src/lib/translation.ts`

## Key Implementation
- Integrate auto-translation (e.g. Swahili, Arabic, Russian to English/Hindi).
- Cache frequent translations to control API costs.
SKILL_EOF

echo "✓ Skills scaffolded"

# ── 4. Copy graduation documents ─────────────────────────────
cp "$IDEA_DIR/vision.md"            "$TARGET/docs/vision.md"
cp "$IDEA_DIR/roadmap.md"           "$TARGET/docs/roadmap.md"
cp "$IDEA_DIR/feasibility.md"       "$TARGET/docs/feasibility.md"
cp "$IDEA_DIR/profitability.md"     "$TARGET/docs/profitability.md"
cp "$IDEA_DIR/agents-blueprint.md"  "$TARGET/docs/agents-blueprint.md"
[ -f "$IDEA_DIR/synthesis.md" ] && cp "$IDEA_DIR/synthesis.md" "$TARGET/docs/synthesis.md" || true
echo "✓ Graduation documents copied to docs/"

# ── 5. Write ADR files ───────────────────────────────────────

cat > "$TARGET/docs/decisions/001-compliance-monetization.md" << 'ADR_EOF'
# ADR 001 — Compliance-First Monetization Model

**Date:** 2026-06-21
**Status:** Accepted

## Context
Traditional medical tourism portals operate on a hospital fee commission structure (typically 15-25% of patient bills). However, in 2023, India's National Medical Commission (NMC) issued strict regulations prohibiting registered medical practitioners and hospitals from participating in referral commission or fee-splitting arrangements for patient procurement. Violation leads to immediate clinical practice bans and hospital closure.

## Decision
CureIndia will strictly reject referral commissions or bill percentage splits. The platform will monetize through:
1. **B2B SaaS Listing Visibility:** Charging premium JCI/NABH hospitals a flat monthly visibility subscription (₹30,000/month) for priority placement and lead workflows.
2. **B2C Flat-Rate Logistics Markups:** Charging patients structured packages for logistics services (airport transit, translators, hotel stays) with a built-in platform margin (~₹15,000 margin per package).

## Rationale
This approach keeps CureIndia fully compliant with NMC regulations, insulates hospital partners from legal exposure, and maintains unbiased platform recommendations based on hospital quality instead of billing size.

## Consequences
- Hospital listing metrics must track engagement performance but never calculate financial commissions based on treatment receipts.
- Flat invoicing mechanisms must be cleanly split between B2B visibility and B2C logistics.
ADR_EOF

cat > "$TARGET/docs/decisions/002-zero-knowledge-vault.md" << 'ADR_EOF'
# ADR 002 — Zero-Knowledge Client-Side Medical Vault

**Date:** 2026-06-21
**Status:** Accepted

## Context
Patient diagnostic documents (MRIs, CT scans, blood reports, clinical histories) are highly sensitive personal data. International regulations like GDPR, HIPAA, and India's Digital Personal Data Protection (DPDP) Act impose severe fines and liability if diagnostic data is exposed, shared without consent, or kept indefinitely in plaintext.

## Decision
All medical records uploaded to CureIndia must be protected via zero-knowledge client-side encryption:
1. The patient's browser generates a symmetric AES-256-GCM key to encrypt the medical PDF/image.
2. The browser fetches the target hospital's public RSA key and encrypts the symmetric AES key with it.
3. The encrypted file is uploaded directly to secure cloud storage (Amazon S3) and the encrypted key is saved in the metadata store.
4. Plaintext files never traverse the network or reside on CureIndia servers. Decryption is performed entirely client-side using the hospital desk's private RSA key.
5. All documents are automatically purged from the vault 30 days post-treatment.

## Rationale
Guarantees absolute compliance with regulatory structures. Ensures that even in the event of a database breach, the files remain unreadable ciphertext.

## Consequences
- Requires high-quality key management modules.
- Imposes small client-side computational latency on upload and download.
ADR_EOF

cat > "$TARGET/docs/decisions/003-quality-curated-directory.md" << 'ADR_EOF'
# ADR 003 — High-Trust Vetted Directory

**Date:** 2026-06-21
**Status:** Accepted

## Context
Medical tourism patients are vulnerable to online fraud, misleading treatment descriptions, and low-quality service providers. Listing unverified clinics or letting unvetted concierge agencies register freely causes immediate trust failure and threatens patient safety.

## Decision
CureIndia will strictly limit listing directories to certified premium providers:
1. Only hospitals holding active JCI (Joint Commission International) or NABH (National Accreditation Board for Hospitals & Healthcare Providers) certifications are allowed.
2. Concierge agencies must pass a digital checklist verification (business licensing check, office physical address verification, background audits) and sign strict service quality agreements (SLAs).
3. Paid visibility placements are restricted to accredited providers; unaccredited clinics are banned from purchasing listings.

## Rationale
Focuses the brand on elite quality and high trust, differentiating CureIndia from existing bulk-intermediaries.

## Consequences
- Limits initial listing volume to 15 hospitals across key hubs (Delhi, Mumbai, Bangalore).
- Requires operational onboarding review gates by administrators.
ADR_EOF

echo "✓ Architecture decision records written"

# ── 6. Write README.md ───────────────────────────────────────
cat > "$TARGET/README.md" << 'README_EOF'
# CureIndia App

A trust-centered, compliance-first marketplace that connects international patients with accredited Indian hospitals and verified local concierge services through transparent package pricing and end-to-end encrypted medical record sharing.

## Tech Stack
- **Frontend/Backend:** Next.js (App Router) + TypeScript
- **Database:** PostgreSQL via Prisma ORM
- **Styling:** CSS Modules / Tailwind CSS
- **Authentication:** NextAuth.js
- **Encryption:** WebCrypto API (Browser-based AES-256-GCM and RSA-OAEP)

## Getting Started

### Prerequisites
- Node.js (v18+)
- PostgreSQL database

### Local Setup
1. Install dependencies:
   ```bash
   npm install
   ```
2. Set up environment:
   ```bash
   cp .env.example .env
   # Fill in your local database credentials and api keys
   ```
3. Sync database schema and run seed:
   ```bash
   npx prisma migrate dev
   npx prisma db seed
   ```
4. Start development server:
   ```bash
   npm run dev
   ```
   The app will run at `http://localhost:3000`.

## Documentation
- [Vision](docs/vision.md) — Product requirements and goals
- [Roadmap](docs/roadmap.md) — Rollout milestones and feature phases
- [Architecture Decisions](docs/decisions/) — ADRs for compliance, encryption, and vetting directories

## Contributing
Open the repository in Antigravity CLI and state the task you want to work on. The system will load the relevant skill (`dev-setup`, `medical-vault`, `quote-portal`, etc.) automatically.
README_EOF
echo "✓ README.md written"

# ── 7. Write .env.example ────────────────────────────────────
cat > "$TARGET/.env.example" << 'ENV_EOF'
# CureIndia — Environment Variables
# Copy to .env and configure local values. Do NOT commit the .env file.

# Database url connection string (PostgreSQL)
DATABASE_URL="postgresql://postgres:postgres@localhost:5454/cure_india?schema=public"

# NextAuth secrets and domain url
NEXTAUTH_SECRET="your_nextauth_jwt_signing_secret_here"
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# AWS S3 Configuration for Encrypted PDF Uploads
AWS_ACCESS_KEY_ID="your_aws_access_key"
AWS_SECRET_ACCESS_KEY="your_aws_secret_key"
AWS_REGION="ap-south-1"
AWS_S3_BUCKET_NAME="cure-india-vault-production"

# Translation API Keys
DEEPL_API_KEY="your_deepl_api_key_here"

# Twilio SMS / WhatsApp alerts
TWILIO_ACCOUNT_SID="your_twilio_sid"
TWILIO_AUTH_TOKEN="your_twilio_auth_token"
ENV_EOF
echo "✓ .env.example written"

# ── 8. Git init ──────────────────────────────────────────────
cd "$TARGET"
git init -q
git add .
git commit -q -m "init: bootstrap from idea-lab graduation"
echo "✓ Git initialized — initial commit made"

# ── Summary ──────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════"
echo "  $REPO_NAME is ready at $TARGET"
echo "════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. cd $TARGET"
echo "  2. Create the GitHub repo and push: gh repo create $REPO_NAME --private && git push -u origin main"
echo "  3. Fill in .env from .env.example"
echo "  4. Spike on the highest-risk dependency (see docs/roadmap.md — Phase 0)"
echo "  5. Open in Antigravity and say: 'set up the dev environment'"
echo ""
export_path=$(cd "$TARGET" && pwd)
echo "Bootstrap completed. Repository root is located at: $export_path"
echo ""
GIF_OK=1
EOF
chmod +x "$TARGET/bootstrap.sh" 2>/dev/null || true
echo "✓ bootstrap.sh marked as executable"
echo ""
echo "Finished!"
